services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_NAME: cycling_tracker
      DB_PORT: 5432
      JWT_SECRET: dev_secret
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cycling_tracker
    ports:
      - "5433:5432"  # ✅ Keep this to avoid local conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  cypress:
    image: cypress/included:12.17.4
    depends_on:
      - app
    working_dir: /e2e
    volumes:
      - .:/e2e  
    environment:
      CYPRESS_baseUrl: http://app:3000
    command: ["cypress", "run"]
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
