name: CI - Docker Compose Full Stack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run full stack tests via Docker Compose
        run: |
          docker-compose -f backend/docker-compose.yml up --build --abort-on-container-exit

      - name: Cleanup
        if: always()
        run: docker-compose -f backend/docker-compose.yml down --volumes
